production:
  adapter: postgresql
  database: development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
 
test:
  adapter: postgresql
  database: development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
  
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: tianzhichen
  password: tianzhic
  host: localhost
  port: 5432