production:
  adapter: postgresql
  database: development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
test:
  adapter: postgresql
  database: development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
# development:
#   adapter: postgresql
#   database: development
#   username: <%= ENV['PG_USER'] %>
#   password: <%= ENV['PG_PASS'] %>
#   host: localhost

development:
  adapter: sqlite3
  database: db/test.sqlite3
